global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'monitorPythonserver'
    static_configs:

      - targets: ['pythonserver:8080']
        labels:
          group: 'monitoring_python'


  - job_name: 'node'
    static_configs:

      - targets: ['node-exporter1:9100']
        labels:
          group: 'monitoring_node_ex1'

      - targets: ['node-exporter2:9100']
        labels:
          group: 'monitoring_node_ex2'

      - targets: ['node-exporter3:9100']
        labels:
          group: 'monitoring_node_ex3'
